name: Deploy Flask App to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create build directory
      run: |
        mkdir -p dist
        
    - name: Copy project files
      run: |
        # Copy templates
        cp -r templates dist/ || echo "No templates directory"
        
        # Copy static files if they exist
        cp -r static dist/ 2>/dev/null || mkdir -p dist/static
        
        # Copy Python files
        cp *.py dist/ 2>/dev/null || echo "No Python files in root"
        
        # Copy models directory
        cp -r models dist/ 2>/dev/null || echo "No models directory"
        
        # Copy uploads directory structure
        mkdir -p dist/uploads
        
        # Copy requirements.txt
        cp requirements.txt dist/ 2>/dev/null || echo "No requirements.txt"
        
        # Copy README
        cp README.md dist/ 2>/dev/null || echo "No README.md"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
